// localhost
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6636bf0f61ab12640dfa00a4
###
GET http://localhost:8080/contacts/6636bf0f61ab12640dfa00a5
###
GET http://localhost:8080/contacts/6636bf0f61ab12640dfa00a6

// render
###
GET https://lesson2-76r3.onrender.com/contacts
###
GET https://lesson2-76r3.onrender.com/contacts/6636bf0f61ab12640dfa00a4
###
GET https://lesson2-76r3.onrender.com/contacts/6636bf0f61ab12640dfa00a5
###
GET https://lesson2-76r3.onrender.com/contacts/6636bf0f61ab12640dfa00a6